// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientMessage = { "type": "subscribe", channel: SubscriptionChannel, market_id: string | null, user_address: string | null, } | { "type": "unsubscribe", channel: SubscriptionChannel, market_id: string | null, user_address: string | null, } | { "type": "ping" };

export type OrderStatus = "pending" | "filled" | "partially_filled" | "cancelled";

export type OrderType = "limit" | "market";

export type OrderbookData = { market_id: string, bids: Array<PriceLevel>, asks: Array<PriceLevel>, };

export type PriceLevel = { price: string, size: string, };

export type ServerMessage = { "type": "subscribed", channel: SubscriptionChannel, market_id: string | null, user_address: string | null, } | { "type": "unsubscribed", channel: SubscriptionChannel, market_id: string | null, user_address: string | null, } | { "type": "trade", trade: TradeData, } | { "type": "orderbook", orderbook: OrderbookData, } | { "type": "order", order_id: string, status: string, filled_size: string, } | { "type": "balance", token_ticker: string, available: string, locked: string, } | { "type": "candle", market_id: string, timestamp: bigint, open: string, high: string, low: string, close: string, volume: string, } | { "type": "error", message: string, } | { "type": "pong" };

export type Side = "buy" | "sell";

/**
 * Channel types for WebSocket subscriptions
 */
export type SubscriptionChannel = "trades" | "orderbook" | "user";

/**
 * Trade data for WebSocket messages (API layer with String fields)
 */
export type TradeData = { id: string, market_id: string, buyer_address: string, seller_address: string, buyer_order_id: string, seller_order_id: string, price: string, size: string, side: Side, timestamp: bigint, };
