/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin endpoint for test/dev operations
         * @description POST /api/admin
         *
         *     Handles administrative operations like creating tokens, markets, and funding accounts.
         *     In production, this endpoint should be protected or disabled.
         */
        post: operations["admin_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get OHLCV candles for a market
         * @description POST /api/candles
         */
        post: operations["get_candles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Drip tokens to users (testing/development faucet) */
        post: operations["drip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get information about tokens, markets, etc. */
        post: operations["info"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute trades (place/cancel orders) */
        post: operations["trade"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get user-specific data (orders, balances, trades) */
        post: operations["user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Admin request with type discriminator */
        AdminRequest: {
            /** Format: int32 */
            decimals: number;
            name: string;
            ticker: string;
            /** @enum {string} */
            type: "create_token";
        } | {
            base_ticker: string;
            lot_size: string;
            /** Format: int32 */
            maker_fee_bps: number;
            min_size: string;
            quote_ticker: string;
            /** Format: int32 */
            taker_fee_bps: number;
            tick_size: string;
            /** @enum {string} */
            type: "create_market";
        } | {
            amount: string;
            signature: string;
            token_ticker: string;
            /** @enum {string} */
            type: "faucet";
            user_address: string;
        };
        /** @description Admin response with type discriminator */
        AdminResponse: {
            token: components["schemas"]["Token"];
            /** @enum {string} */
            type: "create_token";
        } | {
            market: components["schemas"]["ApiMarket"];
            /** @enum {string} */
            type: "create_market";
        } | {
            amount: string;
            new_balance: string;
            token_ticker: string;
            /** @enum {string} */
            type: "faucet";
            user_address: string;
        };
        /** @description API representation of Balance with String fields for JSON compatibility */
        ApiBalance: {
            amount: string;
            open_interest: string;
            token_ticker: string;
            /** Format: date-time */
            updated_at: string;
            user_address: string;
        };
        /** @description OHLCV candle data */
        ApiCandle: {
            close: number;
            high: number;
            low: number;
            open: number;
            /** Format: int32 */
            timestamp: number;
            volume: number;
        };
        /** @description API representation of Market with String fields for JSON compatibility */
        ApiMarket: {
            base_ticker: string;
            id: string;
            lot_size: string;
            /** Format: int32 */
            maker_fee_bps: number;
            min_size: string;
            quote_ticker: string;
            /** Format: int32 */
            taker_fee_bps: number;
            tick_size: string;
        };
        /** @description API representation of Order with String fields for JSON compatibility */
        ApiOrder: {
            /** Format: date-time */
            created_at: string;
            filled_size: string;
            id: string;
            market_id: string;
            order_type: components["schemas"]["OrderType"];
            price: string;
            side: components["schemas"]["Side"];
            size: string;
            status: components["schemas"]["OrderStatus"];
            /** Format: date-time */
            updated_at: string;
            user_address: string;
        };
        ApiResponse: {
            message: string;
            /** Format: int64 */
            timestamp: number;
        };
        /** @description API representation of Trade with String fields for JSON compatibility */
        ApiTrade: {
            buyer_address: string;
            buyer_order_id: string;
            id: string;
            market_id: string;
            price: string;
            seller_address: string;
            seller_order_id: string;
            side: components["schemas"]["Side"];
            size: string;
            /** Format: date-time */
            timestamp: string;
        };
        /** @description Request for OHLCV candles */
        CandlesRequest: {
            count_back?: number | null;
            /** Format: int64 */
            from: number;
            interval: string;
            market_id: string;
            /** Format: int64 */
            to: number;
        };
        /** @description Response containing candles */
        CandlesResponse: {
            candles: components["schemas"]["ApiCandle"][];
        };
        /** @description Drip request with type discriminator */
        DripRequest: {
            amount: string;
            signature: string;
            token_ticker: string;
            /** @enum {string} */
            type: "faucet";
            user_address: string;
        };
        /** @description Drip response with type discriminator */
        DripResponse: {
            amount: string;
            new_balance: string;
            token_ticker: string;
            /** @enum {string} */
            type: "faucet";
            user_address: string;
        };
        ErrorResponse: {
            code: string;
            error: string;
        };
        /** @description Info request with type discriminator */
        InfoRequest: {
            ticker: string;
            /** @enum {string} */
            type: "token_details";
        } | {
            market_id: string;
            /** @enum {string} */
            type: "market_details";
        } | {
            /** @enum {string} */
            type: "all_markets";
        } | {
            /** @enum {string} */
            type: "all_tokens";
        };
        /** @description Info response with type discriminator */
        InfoResponse: {
            token: components["schemas"]["Token"];
            /** @enum {string} */
            type: "token_details";
        } | {
            market: components["schemas"]["ApiMarket"];
            /** @enum {string} */
            type: "market_details";
        } | {
            markets: components["schemas"]["ApiMarket"][];
            /** @enum {string} */
            type: "all_markets";
        } | {
            tokens: components["schemas"]["Token"][];
            /** @enum {string} */
            type: "all_tokens";
        };
        /** @enum {string} */
        OrderStatus: "pending" | "filled" | "partially_filled" | "cancelled";
        /** @enum {string} */
        OrderType: "limit" | "market";
        /** @enum {string} */
        Side: "buy" | "sell";
        Token: {
            /** Format: int32 */
            decimals: number;
            name: string;
            ticker: string;
        };
        /** @description Trade request with type discriminator */
        TradeRequest: {
            market_id: string;
            order_type: components["schemas"]["OrderType"];
            price: string;
            side: components["schemas"]["Side"];
            signature: string;
            size: string;
            /** @enum {string} */
            type: "place_order";
            user_address: string;
        } | {
            order_id: string;
            signature: string;
            /** @enum {string} */
            type: "cancel_order";
            user_address: string;
        } | {
            market_id?: string | null;
            signature: string;
            /** @enum {string} */
            type: "cancel_all_orders";
            user_address: string;
        };
        /** @description Trade response with type discriminator */
        TradeResponse: {
            order: components["schemas"]["ApiOrder"];
            trades: components["schemas"]["ApiTrade"][];
            /** @enum {string} */
            type: "place_order";
        } | {
            order_id: string;
            /** @enum {string} */
            type: "cancel_order";
        } | {
            cancelled_order_ids: string[];
            count: number;
            /** @enum {string} */
            type: "cancel_all_orders";
        };
        /** @description User request with type discriminator */
        UserRequest: {
            /** Format: int32 */
            limit?: number | null;
            market_id?: string | null;
            status?: string | null;
            /** @enum {string} */
            type: "orders";
            user_address: string;
        } | {
            /** @enum {string} */
            type: "balances";
            user_address: string;
        } | {
            /** Format: int32 */
            limit?: number | null;
            market_id?: string | null;
            /** @enum {string} */
            type: "trades";
            user_address: string;
        };
        /** @description User response with type discriminator */
        UserResponse: {
            orders: components["schemas"]["ApiOrder"][];
            /** @enum {string} */
            type: "orders";
        } | {
            balances: components["schemas"]["ApiBalance"][];
            /** @enum {string} */
            type: "balances";
        } | {
            trades: components["schemas"]["ApiTrade"][];
            /** @enum {string} */
            type: "trades";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    admin_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminRequest"];
            };
        };
        responses: {
            /** @description Admin operation successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_candles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandlesRequest"];
            };
        };
        responses: {
            /** @description Candles retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandlesResponse"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    drip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DripRequest"];
            };
        };
        responses: {
            /** @description Tokens dripped successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DripResponse"];
                };
            };
            /** @description Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid signature */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Token not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health check response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InfoRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    trade: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradeRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeResponse"];
                };
            };
            /** @description Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid signature */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description User or resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
